url : https://colossus9.github.io
code : https://github.com/colossus9/colossus9.github.io
title : James Garcia
subtitle : About Me

author :
  name : James Garcia
  email : mailto:jrgarcia786@gmail.com
  description : Get to know me
  markdown : https://github.com/colossus9/colossus9.github.io/blob/master/Profile.md
  linkedin: https://www.linkedin.com/in/jrgarcia786
  github : https://github.com/colossus9
  twitter : https://twitter.com/c0l0ssus9
  facebook : https://www.facebook.com/c0lossus9
  forj : http://h41367.www4.hpe.com/campaigns/IT_Experts/pages/forj.html
  resume : https://github.com/colossus9/colossus9.github.io/blob/master/Resume.pdf
  credits : credits.html

markdown : kramdown
highlighter : rouge
baseurl :

# Default date format is "ordinal" (resulting in "July 22nd 2016")
# You can customize the format as defined in
# http://www.ruby-doc.org/core-1.9.2/Time.html#method-i-strftime
# Additionally, %o will give you the ordinal representation of the day
date_format: "ordinal"
