url : https://pages.github.hpe.com/james-rob-garcia/
title : James Garcia
subtitle : About Me

author :
  name : James Garcia
  email : mailto:jrgarcia786@gmail.com
  description : Get to know me
  linkedin: https://www.linkedin.com/in/jrgarcia786
  github : https://github.com/colossus9
  twitter : https://twitter.com/c0l0ssus9
  facebook : http://www.facebook.com/c0lossus9
  resume : Resume.md

markdown : kramdown
highlighter : rouge
baseurl : /james-rob-garcia

# Default date format is "ordinal" (resulting in "July 22nd 2016")
# You can customize the format as defined in
# http://www.ruby-doc.org/core-1.9.2/Time.html#method-i-strftime
# Additionally, %o will give you the ordinal representation of the day
date_format: "ordinal"
